[project]
name = "skin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["skin-ai", "oxapy>=0.8.0"]

[tool.uv.workspace]
members = ["skin-ai", "api", "bot"]

[tool.uv.sources]
skin-ai = { workspace = true }
