[project]
name = "skin-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "numpy>=2.4.0",
  "keras>=3.13.0",
  "opencv-python>=4.11.0.86",
  "tensorflow>=2.20.0",
]
